import type { ManagedInvoice } from "@/lib/db/invoice-record";

export const SAMPLE_INVOICE_ID = "5b2f8c1e-7a4d-4e6b-9c3f-2d1e0a9b8c7d";
export const SAMPLE_BOOKING_ID = "0b7e4f6a-2c3d-4e5f-8a9b-1c2d3e4f5a6b";
export const SAMPLE_CUSTOMER_ID = "1c2d3e4f-5a6b-4c7d-8e9f-0a1b2c3d4e5f";
export const SAMPLE_ISSUER_NAME = "Example Test Trading Co";
export const SAMPLE_TRN = "100000000000003";
export const SUITE_WITH_NUMBER = /\bsuite\s*(?:no\.?|number|#)?\s*\d/i;

export function sampleInvoice(overrides: Partial<ManagedInvoice> = {}): ManagedInvoice {
  return {
    id: SAMPLE_INVOICE_ID,
    invoiceNumber: "INV-2026-000042",
    sequenceNo: 42,
    bookingId: SAMPLE_BOOKING_ID,
    customerId: SAMPLE_CUSTOMER_ID,
    issuedAt: "2026-09-11T20:30:00.000Z",
    issuedBy: null,
    issuer: {
      legalName: SAMPLE_ISSUER_NAME,
      trn: SAMPLE_TRN,
      address: "Unit 1, Example Street\nTest City, UAE",
    },
    billTo: {
      salutation: "ms",
      firstName: "Amina",
      lastName: "Tester",
      name: "Amina Tester",
      email: "guest@example.test",
      phoneE164: "+971500000000",
    },
    lines: [
      {
        kind: "visit",
        label: "Visit",
        quantity: null,
        unitPriceFils: null,
        amountFils: 66000,
        isIncluded: false,
        isTaxable: null,
        minutes: null,
        adults: 2,
        children: 1,
        startsAt: "2026-09-12T10:00:00.000Z",
        endsAt: "2026-09-12T13:00:00.000Z",
      },
      {
        kind: "addon",
        label: "Bathrobe",
        quantity: 2,
        unitPriceFils: 2500,
        amountFils: 5000,
        isIncluded: false,
        isTaxable: true,
        minutes: null,
        adults: null,
        children: null,
        startsAt: null,
        endsAt: null,
      },
      {
        kind: "addon",
        label: "Towel",
        quantity: 3,
        unitPriceFils: 0,
        amountFils: 0,
        isIncluded: true,
        isTaxable: true,
        minutes: null,
        adults: null,
        children: null,
        startsAt: null,
        endsAt: null,
      },
      {
        kind: "discount",
        label: "Discount",
        quantity: null,
        unitPriceFils: null,
        amountFils: -6600,
        isIncluded: false,
        isTaxable: null,
        minutes: null,
        adults: null,
        children: null,
        startsAt: null,
        endsAt: null,
      },
      {
        kind: "service_fee",
        label: "Service Fee",
        quantity: null,
        unitPriceFils: null,
        amountFils: 3864,
        isIncluded: false,
        isTaxable: null,
        minutes: null,
        adults: null,
        children: null,
        startsAt: null,
        endsAt: null,
      },
    ],
    tax: { label: "VAT", ratePercent: 5, isIncluded: true },
    subtotalFils: 66000,
    discountFils: 6600,
    addonsFils: 5000,
    serviceFeeFils: 3864,
    taxFils: 3067,
    taxableFils: 61333,
    overrunFils: 0,
    totalFils: 68264,
    paidFils: 68264,
    currency: "AED",
    voidedAt: null,
    voidedBy: null,
    voidReason: null,
    bookingReference: "WPTEST01",
    suiteId: "9f8e7d6c-5b4a-4c3d-8e2f-1a0b9c8d7e6f",
    suiteNumber: 3,
    customerName: "Amina Tester",
    customerEmail: "guest@example.test",
    issuedByName: "Test Manager",
    voidedByName: null,
    state: "issued",
    ...overrides,
  };
}
