import {
  VENUE_LOCALITY,
  VENUE_MAP_CENTER,
  VENUE_MAP_ZOOM,
} from "@/lib/config/entity";

export const HOME_PAGE_CONTENT = {
  hero: {
    title: "Step out of the world",
    accent: "Into your own",
    body: "A first-of-its-kind private wellness concept in the UAE, with a complete suite reserved just for you.",
    primaryLabel: "Check availability and pricing",
    secondaryLabel: "Explore the suites",
    mediaLabel: "WellPlace reception, lounge and private wellness interiors",
    slides: [
      "/renderings/reception-sitting-areaa-view-2-1920.webp",
      "/renderings/reception-sitting-areaa-view-4-1920.webp",
      "/renderings/reception-sitting-areaa-view-3-1920.webp",
      "/renderings/reception-sitting-areaa-view-6-1920.webp",
      "/renderings/reception-sitting-areaa-view-7-1920.webp",
    ],
  },
  difference: {
    eyebrow: "The WellPlace difference",
    revealLabel: "Reveal more",
    swipeHint: "Swipe to explore",
    title: "Privacy changes the way",
    accent: "time feels",
    cards: [
      {
        label: "Private by default",
        title: "Everything behind one door",
        backLabel: "Private by default",
        backTitle: "Everything behind one door",
        icon: "key",
        detail:
          "A complete wellness experience brought together inside one private suite.",
        action: "Discover the suites",
        image: "/renderings/suite-view-1-960.webp",
      },
      {
        label: "Time, unhurried",
        title: "Never shared",
        backLabel: "Time, unhurried",
        backTitle: "Never shared",
        icon: "clock",
        detail:
          "The entire suite is reserved exclusively for you and the people you choose.",
        action: "Explore the space",
        image: "/renderings/reception-sitting-areaa-view-3-960.webp",
      },
      {
        label: "The people you choose",
        title: "Your time, your rhythm",
        backLabel: "The people you choose",
        backTitle: "Your time, your rhythm",
        icon: "users",
        detail:
          "Choose two to six hours for two to five guests and experience the suite entirely at your own pace.",
        action: "Read common questions",
        image: "/renderings/reception-sitting-areaa-view-7-960.webp",
      },
    ],
  },
  suite: {
    eyebrow: "Inside a suite",
    ctaLabel: "Check availability and pricing",
    views: [
      {
        label: "Rest",
        title: "A suite built around",
        emphasis: "stillness",
        body: "Warm stone, soft light, and everything set before you arrive. Each suite is a complete world behind one door.",
        detailTitle: "Your relaxation lounge",
        detailBody: "Space to sit, talk or simply be quiet together.",
        image: "/renderings/suite-view-2-1920.webp",
        imageAlt: "A warm private WellPlace suite with a relaxation daybed, lounge and whirlpool",
      },
      {
        label: "Lounge",
        title: "Settle into",
        emphasis: "your own rhythm",
        body: "The suite gives your guests room to arrive, slow down and spend the session exactly as you choose.",
        detailTitle: "Climate, light & sound you control",
        detailBody: "Set the mood from a single panel.",
        image: "/renderings/suite-view-3-1920.webp",
        imageAlt: "A private WellPlace relaxation lounge beside the suite lounge",
      },
      {
        label: "Warmth",
        title: "Wellness held",
        emphasis: "behind one door",
        body: "Move between warmth, water and rest without leaving the calm and privacy of your own suite.",
        detailTitle: "A wellness space kept private",
        detailBody: "No shared suite, no interruption and no need to rush.",
        image: "/renderings/suite-view-4-1920.webp",
        imageAlt: "A wood-lined wellness suite inside a private WellPlace suite",
      },
      {
        label: "Water",
        title: "Water and time",
        emphasis: "entirely yours",
        body: "Choose the pace, temperature and atmosphere, with every part of the private water area reserved for your guests.",
        detailTitle: "Private whirlpool & experience shower",
        detailBody: "Your own water, temperature and time.",
        image: "/renderings/suite-view-6-1920.webp",
        imageAlt: "The whirlpool and cold plunge inside a private WellPlace suite",
      },
    ],
  },
  bridge: {
    image: "/renderings/reception-sitting-areaa-view-8-1920.webp",
  },
  gallery: {
    viewerCaption: "A larger view of this WellPlace space.",
    // [OWNER, 15 Sep] Nine-image local preview proposal; final client selection is pending.
    shots: [
      {"image": "/renderings/suite-view-6-1920.webp", "alt": "The private sauna and experience shower inside a WellPlace suite", "orientation": "landscape"},
      {"image": "/renderings/suite-view-4-1920.webp", "alt": "An overhead view of the complete private suite and its facilities", "orientation": "portrait"},
      {"image": "/renderings/suite-view-1-1920.webp", "alt": "The reception desk and sitting area framed by stone and greenery", "orientation": "landscape"},
      {"image": "/renderings/reception-sitting-areaa-view-4-1920.webp", "alt": "The reception lounge and refreshment counter", "orientation": "landscape"},
      {"image": "/renderings/reception-sitting-areaa-view-5-960.webp", "alt": "Stone detailing at the refreshment counter", "orientation": "landscape"},
      {"image": "/renderings/reception-sitting-areaa-view-6-960.webp", "alt": "A quiet seating area beside reception", "orientation": "landscape"},
      {"image": "/renderings/suite-view-8-960.webp", "alt": "The stone staircase with warm integrated lighting", "orientation": "portrait"},
      {"image": "/renderings/suite-view-3-1920.webp", "alt": "The softly lit corridor leading to the private suites", "orientation": "portrait"},
      {"image": "/renderings/reception-sitting-areaa-view-7-960.webp", "alt": "Sculptural artwork and timber detailing along the corridor", "orientation": "portrait"},
    ],
    eyebrow: "The space",
    title: "Move through",
    accent: "the details",
    body: "Every view reveals a different part of the experience. Open one, then move through the full collection.",
  },
  faq: {
    // [§Owner Home FAQ reference, 15 Sep] Existing reception rendering for the image column.
    image: "/renderings/reception-sitting-areaa-view-5-1920.webp",
    imageAlt: "The WellPlace reception desk framed by warm stone and greenery",
    eyebrow: "FAQs",
    title: "Frequently asked",
    accent: "questions",
    body: "A few helpful details before your visit.",
    linkLabel: "View all FAQs",
  },
  location: {
    eyebrow: "Find us",
    title: "Business Bay,",
    accent: "Dubai",
    body: "A private wellness destination tucked into Dubai’s creative industrial district.",
    openMapLabel: "Open map",
    directionsLabel: "Get directions",
    mapLabel: "View larger map",
    locality: VENUE_LOCALITY,
    latitude: String(VENUE_MAP_CENTER[0]),
    longitude: String(VENUE_MAP_CENTER[1]),
    mapZoom: String(VENUE_MAP_ZOOM),
  },
} as const;
