import type { PriceTier } from "@/lib/domain/pricing";

export const LAUNCH_PRICE_TIERS: readonly PriceTier[] = [
  {
    id: "adult-first-two",
    guestKind: "adult",
    fromHour: 1,
    toHour: 2,
    regularFilsPerHour: 22_000,
    offerFilsPerHour: 16_500,
    offerPercent: null,
    weekdays: null,
    seasonFrom: null,
    seasonTo: null,
    startWindow: null,
    priority: 0,
  },
  {
    id: "adult-additional",
    guestKind: "adult",
    fromHour: 3,
    toHour: null,
    regularFilsPerHour: 22_000,
    offerFilsPerHour: 14_000,
    offerPercent: null,
    weekdays: null,
    seasonFrom: null,
    seasonTo: null,
    startWindow: null,
    priority: 0,
  },
  {
    id: "child-first-two",
    guestKind: "child",
    fromHour: 1,
    toHour: 2,
    regularFilsPerHour: 17_000,
    offerFilsPerHour: 12_750,
    offerPercent: null,
    weekdays: null,
    seasonFrom: null,
    seasonTo: null,
    startWindow: null,
    priority: 0,
  },
  {
    id: "child-additional",
    guestKind: "child",
    fromHour: 3,
    toHour: null,
    regularFilsPerHour: 17_000,
    offerFilsPerHour: 11_000,
    offerPercent: null,
    weekdays: null,
    seasonFrom: null,
    seasonTo: null,
    startWindow: null,
    priority: 0,
  },
];
